site_name: lernOS ePortfolio Guide
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/en

nav:
    - About lernOS: index.md
    - Basics: 1-0-Basics.md
    - Learning Pathway:
        - Learning Pathway Overview: 2-0-Learning-Pathway.md
        - Learning area 1 - Get to know: 2-1-Learning-area-1.md
        - Learning area 2 - Topic interest: 2-1-Learning-area-2.md
        - Learning area 3 - ePortfolio tools: 2-1-Learning-area-3.md
        - Learning area 4 - Topic article and learning reflection: 2-1-Learning-area-4.md
        - Learning area 5 - Networking: 2-1-Learning-area-5.md
        - Learning area 6 - Topic plan: 2-1-Learning-area-6.md
        - Learning area 7 - Feedback / Lessons learned: 2-1-Learning-area-7.md
    - Lessons Learned: 3-0-Lessons-Learned.md
    - Appendix: 4-0-Appendix.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-eportfolio/blob/master/de/lernOS-ePortfolio-Guide-de.pdf
      - Word-Version: https://github.com/cogneon/lernos-eportfolio/blob/master/de/lernOS-ePortfolio-Guide-de.docx
      - HTML-Version: https://github.com/cogneon/lernos-eportfolio/blob/master/de/lernOS-ePortfolio-Guide-de.html
      - E-Book (epub): https://github.com/cogneon/lernos-eportfolio/blob/master/de/lernOS-ePortfolio-Guide-de.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-eportfolio/blob/master/de/lernOS-ePortfolio-Guide-de.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-eportfolio'
repo_url: 'https://github.com/cogneon/lernos-eportfolio'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom
    alternate:
      - name: English
        link: ../en/
        lang: en
      - name: German
        link: ../de/
        lang: de

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
