site_name: lernOS ePortfolio Guide
site_url: https://cogneon.github.io/

docs_dir: src

site_dir: ../docs/de

nav:
    - About lernOS: index.md
    - Basics: 1-Grundlagen.md
    - Learning Pathway:
        - Learning Pathway Overview: 2-0-Lernpfad.md
        - Learning area 1 - Get to know: 2-1-Lernbereich-1.md
        - Learning area 2 - Topic interest: 2-1-Lernbereich-2.md
        - Learning area 3 - ePortfolio tools: 2-1-Lernbereich-3.md
        - Learning area 4 - Topic article and learning reflection: 2-1-Lernbereich-4.md
        - Learning area 5 - Networking: 2-1-Lernbereich-5.md
        - Learning area 6 - Topic plan: 2-1-Lernbereich-6.md
        - Learning area 7 - Feedback / Lessons learned: 2-1-Lernbereich-7.md
    - Lessons Learned: 3-Lessons-Learned.md
    - Appendix: 4-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-eportfolio'
repo_url: 'https://github.com/cogneon/lernos-eportfolio'

google_analytics:
  - 'UA-156969141-1'
  - 'auto'

extra:
#    social:
#        - type: 'twitter'
#          link: 'https://twitter.com/lern_os'
#        - type: 'linkedin'
#          link: 'https://www.linkedin.com/showcase/lern-os'
#        - type: 'github'
#          link: 'https://github.com/cogneon'
    disqus: lernos
