site_name: lernOS ePortfolio Guide
site_url: https://cogneon.github.io/

docs_dir: src

site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen: 1-Grundlagen.md
    - Lernpfad:
        - Lernpfad Überblick: 2-0-Lernpfad.md
        - Lernbereich 1 - Kennenlernen: 2-1-Lernbereich-1.md
        - Lernbereich 2 - Themeninteresse: 2-1-Lernbereich-2.md
        - Lernbereich 3 - ePortfolio-Werkzeuge: 2-1-Lernbereich-3.md
        - Lernbereich 4 - Themenbeitrag und Lernreflexio: 2-1-Lernbereich-4.md
        - Lernbereich 5 - Vernetzun: 2-1-Lernbereich-5.md
        - Lernbereich 6 - Themenplan: 2-1-Lernbereich-6.md
        - Learning area 7 - Feedback / Lessons learned: 2-1-Lernbereich-7.md
    - Lessons Learned: 3-Lessons-Learned.md
    - Anhang: 4-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-eportfolio'
repo_url: 'https://github.com/cogneon/lernos-eportfolio'

google_analytics:
  - 'UA-156969141-1'
  - 'auto'

extra:
#    social:
#        - type: 'twitter'
#          link: 'https://twitter.com/lern_os'
#        - type: 'linkedin'
#          link: 'https://www.linkedin.com/showcase/lern-os'
#        - type: 'github'
#          link: 'https://github.com/cogneon'
    disqus: lernos
